amannn/next-intl

CHANGELOG.md
README.md
packages/example/package.json
packages/next-intl/package.json
packages/use-intl/package.json
packages/use-intl/src/IntlContext.tsx
packages/use-intl/src/IntlError.tsx
packages/use-intl/src/IntlProvider.tsx
packages/use-intl/src/index.tsx
packages/use-intl/src/useIntlContext.tsx
packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useTranslations.test.tsx
packages/use-intl/tsconfig.json

Fixes #8
Minor differences to the proposal:
- No `level` (the user can decide how critical a given `code` is).
- All errors except for the missing provider can render a fallback message and therefore simply log an error to the console instead of breaking the app.

Revamped error handling

---

CHANGELOG.md
packages/use-intl/src/useTranslations.tsx

Fixes #27 by ensuring we return `string | ReactElement | ReactNodeArray`.

fix: Limit the function signature to return strings or React elements

---

packages/next-intl/package.json
packages/next-intl/tsconfig.json
packages/use-intl/package.json
packages/use-intl/src/NumberFormatOptions.tsx
packages/use-intl/src/TranslationValues.tsx
packages/use-intl/src/index.tsx
packages/use-intl/src/useIntl.tsx
packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useIntl.test.tsx
packages/use-intl/test/useTranslations.test.tsx
packages/use-intl/tsconfig.json
yarn.lock

- Use enum type for style of NumberFormatOptions
- Only allow function children for translation values of `t.raw`
- Update TypeScript and `tslib`

feat: Use enum type for `style` of `NumberFormatOptions`

---

packages/example/messages/de.json
packages/example/messages/en.json
packages/example/src/components/PageLayout.tsx
packages/example/src/pages/404.tsx
packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useTranslations.test.tsx

… and provide a 404 example.
Closes #65

fix: Clearer error message when no messages are provided

---

packages/example-advanced/.eslintrc.js
packages/example-advanced/config/babel.config.js
packages/example-advanced/config/jest.json
packages/example-advanced/package.json
packages/example-advanced/src/components/Navigation.spec.tsx
packages/example-advanced/src/components/Navigation.tsx
packages/example-advanced/tsconfig.json
packages/next-intl/src/NextIntlProvider.tsx
packages/website/pages/docs/faq.mdx
yarn.lock

fix: Allow usage outside of Next.js (e.g. Jest and Storybook)

---

packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useTranslations.test.tsx

fix: Support identical wrappers with identical text content in rich text

---

packages/use-intl/src/IntlContext.tsx
packages/use-intl/src/IntlProvider.tsx
packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useIntl.test.tsx
packages/use-intl/test/useTranslations.test.tsx
packages/website/pages/docs/usage/configuration.mdx
packages/website/pages/docs/usage/messages.mdx

To achieve consistent usage and styling of rich text elements, I have included an option to define global defaults for rich text elements. The default will be overridden by a local definition of an element.
This approach is the same as the one from [react-intl](https://formatjs.io/docs/react-intl/components/#defaultrichtextelements).

feat: Default translation values

---

packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useTranslations.test.tsx

fix: Add back ability to render without messages

---

packages/use-intl/src/useTranslations.tsx

Fixes #112 
Modified files:
- `packages/use-intl/src/useTranslations.tsx`
It's just my comment with the ideas applied:
> And in the conditional, I just check if `NestedKey` is `never`: `[NestedKey] extends [never] ? ... : ...`. It seems to work fine.
> 
> You can find the fix [here](https://www.typescriptlang.org/play?#code/PTAEFpM0FcBcCWAbAzgWAFCbgTwA4CmoAcgSnAQCYDSBOA8gGYA89AfKALyj2gEAeFAHaUUoAPYAjAFYEAxnFAB+UAG9MoTaADa1UAiGgA1nXGMeAXQBcoAAYASVXoBkocgCcDAcwC+t0AA+do4ubnCeQr4AdI6k5FS0DCz0uhZsfgDcmD7aJjhmlqA2QgQAbgTuWVgYuISgAOIEcKwANKAACnyCBCJiHt4cnBodXcKiwaoGjBWgiT4xk0LT7qAASmRwfsOaKomjPeN5Bbwqjc0piRZt6+QcxWUV20UjAmNiR+YnPNrtFs8l5UqmGw+CIZ3oMnkcESKFas32vTCES8gzUwx++kM1GsDSacPaHFeBz64W8ylAAJmNnaVRy2KqmBAECg4H0AFs8EgCGyenAAIaIcRCYEYJkAIXc4hMwuqciF5AkMi4aIwmkkfPcNnUqq0fJsAHIABIEJBIcT64Y+bKgP …

fix: #112 - default NestedKey to never

---

README.md
packages/website/pages/docs/meta.json
packages/website/pages/docs/next-13.mdx
packages/website/pages/index.mdx

docs: Add docs for Next.js 13 and the `app` directory

---

packages/next-intl/src/client/usePathname.tsx

```
error - ./node_modules/.pnpm/next-intl@2.11.0-beta.8_next@13.1.6+react@18.2.0/node_modules/next-intl/dist/src/client/usePathname.js
ReactServerComponentsError:
You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
,-[./node_modules/.pnpm/next-intl@2.11.0-beta.8_next@13.1.6+react@18.2.0/node_modules/next-intl/dist/src/client/usePathname.js:1:1]
1 | import { usePathname as useNextPathname } from 'next/navigation';
2 | import { useEffect, useState } from 'react';
:                     ^^^^^^^^
3 | import getCookieLocale from './getCookieLocale';
4 | import hasPathnamePrefixed from './hasPathnamePrefixed';
5 | export function unlocalizePathname(pathname) {
`---- …
```

fix: add missing 'use client' directive for usePathname

---

packages/website/pages/docs/next-13/server-components.mdx

This fixes the wrong path in `server-components.mdx`.  the Folder `messages` and `i18n.ts` are at the same level.

docs: fix path in server-components.mdx

---

packages/next-intl/src/server/resolveLocale.tsx

Any errors thrown by `Intl.getCanonicalLocales` should be catched and the default language should be returned. 
I noticed this because cypress was setting the `accept-language` header to `*`.

fix: Incorrect locale information provided Error if accept-language is invalid

---

packages/example-next-13-advanced/next.config.js
packages/example-next-13-advanced/package.json
packages/example-next-13-advanced/src/middleware.ts
packages/example-next-13-advanced/tests/main.spec.ts
packages/website/pages/docs/next-13/server-components.mdx
yarn.lock

Unfortunately [Vercel doesn't support the `vary` header](https://github.com/vercel/vercel/discussions/7612#discussioncomment-2434736) currently which is used by RSC to differentiate prefetch requests, this [breaks page navigation](https://github.com/amannn/street-photography-viewer/pull/2).
Potential solutions:
- Vercel supports `vary`
- We can detect prefetch requests in the middleware to not cache those
- Add caching via `next.config.js` or `vercel.json` and opt-out of prefetch header?

feat: Next.js 13 RSC caching

---

packages/example-next-13-advanced/package.json
packages/example-next-13-advanced/src/middleware.ts
packages/example-next-13-advanced/tests/main.spec.ts
packages/example-next-13/next-env.d.ts
packages/next-intl/plugin.js
packages/next-intl/src/client/usePathname.tsx
packages/next-intl/src/middleware/NextIntlMiddlewareConfig.tsx
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/resolveLocale.tsx
packages/next-intl/test/middleware/getAlternateLinksHeaderValue.test.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/website/pages/docs/next-13/server-components.mdx
yarn.lock

Improvements: 
- Switch to a new API in the middleware to configure advanced routing patterns (please see [the updated docs](https://next-intl-git-feat-next-13-rsc-middleware-improvements-amann.vercel.app/docs/next-13/server-components#middleware-configuration))
- Support mode to always prefix the current route with the locale
- Improve domain-based routing to allow redirects from one domain to another and better integrate with alternate links (only show domain-alternatives)

feat: Next.js 13 RSC middleware improvements

---

packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/test/core/createFormatter.test.tsx
packages/use-intl/test/react/useFormatter.test.tsx

Added a single `BigInt` test to each  `createFormatter` and `useFormatter`. I also noticed was no test for plain-old 'number' without currency. I thought it made sense to have one so I broke the existing test into two.
Closes #222

feat: BigInt support for useFormatter.format() (#222)

---

packages/example-next-13-advanced/src/middleware.ts
packages/next-intl/.eslintrc.js
packages/next-intl/package.json
packages/next-intl/src/middleware/NextIntlMiddlewareConfig.tsx
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/getHost.tsx
packages/next-intl/src/middleware/getLocaleFromPathname.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/resolveLocale.tsx
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/test/client/NextIntlClientProvider.test.tsx
packages/next-intl/test/middleware/getAlternateLinksHeaderValue.test.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/website/.gitignore
packages/website/pages/docs/next-13/server-components.mdx
yarn.lock

**Changes:**
- Allow domain-based routing to handle multiple locales (e.g. `ca.example.com/fr`)
- Support `localePrefix` for domain-based routing
- Handle unknown hosts like `localhost` gracefully with domain-based routing
- Add `localeDetection: false` option
- Improve matcher suggestion in docs
Please see the updated docs to learn more.

feat: Next.js 13 RSC Domain middleware improvements

---

packages/next-intl/plugin.d.ts
packages/next-intl/plugin.js

The default configuration object provided when [dynamically constructing](https://nextjs.org/docs/api-reference/next.config.js/introduction) the Next.js configuration sets the `i18n` property to `null`, this causes `withNextIntl` to incorrectly emit a warning about the use of Next.js' builtin `i18n` library.
Additionally `withNextIntl` incorrectly types the `i18nPath` as `string` when it should be `string | undefined`.

fix: invalid i18n warning

---

packages/next-intl/src/link/Link.tsx
packages/next-intl/test/link/Link.test.tsx

fix: Accept `ref` for `next-intl/link`

---

.github/workflows/main.yml
.github/workflows/publish.yml
docs/next.config.js
docs/package.json
docs/pages/_app.tsx
examples/example-next-13-next-auth/next.config.js
examples/example-next-13/next.config.js
examples/example-next-13/package.json
examples/example-next-13/src/app/[locale]/layout.tsx
pnpm-lock.yaml

Changes:
- Removed experimental config for appDir because starting from nextjs v13.4, this feature is stable (for now in the console at development mode we have some warns about that this config is necessary but it was fixed in the latest version of nextjs),
- Removed the `@next/font` package since it is now built into nextjs itself.

refactor: Remove experimental config for appDir and @next/font

---

packages/next-intl/src/client/useClientLocale.tsx
packages/next-intl/src/client/usePathname.tsx
packages/next-intl/src/shared/BaseLink.tsx
packages/next-intl/test/client/usePathname.test.tsx
packages/next-intl/test/link/Link.test.tsx

fix: Allow usage of `next-intl/link` and `usePathname` outside of Next.js

---

examples/example-next-13-advanced/src/app/[locale]/layout.tsx
examples/example-next-13-advanced/src/i18n.tsx
examples/example-next-13-advanced/tests/main.spec.ts
examples/example-next-13/src/app/[locale]/layout.tsx
packages/next-intl/src/react-server/useFormatter.tsx
packages/next-intl/src/react-server/useLocale.tsx
packages/next-intl/src/react-server/useNow.tsx
packages/next-intl/src/react-server/useTimeZone.tsx
packages/next-intl/src/react-server/useTranslations.tsx
packages/next-intl/src/server/getConfig.tsx
packages/next-intl/src/server/getFormatter.tsx
packages/next-intl/src/server/getIntl.tsx
packages/next-intl/src/server/getLocale.tsx
packages/next-intl/src/server/getLocaleFromHeader.tsx
packages/next-intl/src/server/getNow.tsx
packages/next-intl/src/server/getTimeZone.tsx
packages/next-intl/src/server/getTranslations.tsx
packages/next-intl/src/server/getTranslator.tsx
packages/next-intl/src/server/index.tsx
packages/next-intl/src/server/redirect.tsx

The currently available APIs for using `next-intl` outside of components like `getTranslations` work well, but are limited to SSR. Using `useTranslations` in components is technically also limited to SSR at this point, but I have high hopes that React Server Context will eventually enable those to work for SSG too.
However, React Server Context will not be available in functions like `generateMetadata` as this happens outside of the React render as far as I understand. Therefore we should provide APIs that anticipate this change. In the unlikely event that React Server Context will work somehow in these functions, we can still make the passed `locale` optional, but the transition will be smooth here. Moving to this new API rather sooner than later is a good idea to avoid churn.
**Before** …

feat: New APIs for using `next-intl` outside of components

---

docs/pages/docs/usage/dates-times.mdx

```diff
- If you're formatting dates and times, you should [set up a global time zone](#/docs/usage/configuration#time-zone).
+ If you're formatting dates and times, you should [set up a global time zone](/docs/usage/configuration#time-zone).
```

Fix: small typo that breaks a link

---

packages/next-intl/src/server/index.tsx
packages/next-intl/src/server/react-client/index.tsx

fix(Next.js 13 RSC): Fix types when importing from `next-intl/server` with `moduleResolution: "node16"`

---

packages/next-intl/dts.config.js
packages/next-intl/package.json
packages/next-intl/src/react-server/getBaseTranslator.tsx
packages/next-intl/src/react-server/useTranslations.tsx
packages/next-intl/src/server/getTranslations.tsx
packages/next-intl/test/server/getTranslator.test.tsx
packages/use-intl/dts.config.js
pnpm-lock.yaml

To be in sync with the `createTranslator` API

fix(RSC): Return `string` from `(await getTranslator()).rich`

---

docs/pages/docs/environments/_meta.json
docs/pages/docs/environments/error-files.mdx
docs/pages/docs/environments/index.mdx
examples/example-next-13/messages/de.json
examples/example-next-13/messages/en.json
examples/example-next-13/src/app/[locale]/error.tsx
examples/example-next-13/src/app/[locale]/page.tsx
examples/example-next-13/src/app/not-found.tsx

Fixes #400
Related: https://github.com/amannn/next-intl/discussions/329 #336

docs: Add error handling docs

---

docs/pages/docs/environments/error-files.mdx
docs/pages/docs/routing/navigation.mdx
examples/example-next-13/src/components/LocaleSwitcher.tsx
packages/next-intl/src/client/useRouter.tsx
packages/next-intl/test/client/useRouter.test.tsx

feat: Accept `locale` with `useRouter` APIs

---

docs/pages/docs/routing/middleware.mdx
packages/next-intl/src/middleware/NextIntlMiddlewareConfig.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/middleware.test.tsx

feat: add LocalePrefix never option

---

docs/package.json
examples/example-advanced/package.json
examples/example-next-13-next-auth/package.json
examples/example-next-13/package.json
examples/example-next-13/tests/main.spec.ts
examples/example/package.json
packages/next-intl/package.json
packages/next-intl/src/client/useClientLocale.tsx
packages/next-intl/src/middleware/middleware.tsx
pnpm-lock.yaml

Changes:
- Handle case where the locale param is an array
- Set cookie expiration to one year
- Pin Next.js version in examples
- Use `latest` tag in examples (for CSB)
Fixes #431

fix: Handle case where the `locale` param is an array and set cookie expiration to one year

---

examples/example-next-13-next-auth/src/components/LocaleSwitcher.tsx

improves locale switcher by making use of next-intl/link to be able to switch without losing current page

feat: add next-intl/link to be used in locale switcher in next 13 example

---

packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/getAlternateLinksHeaderValue.test.tsx

We are currently utilizing a reverse proxy in front of Next.js.
`request.url` is returning an internal address instead of an external one.
Consequently, the rewrite functionality is not behaving as expected, and the `alternatelink` header is inadvertently exposing the internal address.

fix: Detect host and protocol for alternate links correctly when running behind a proxy

---

docs/pages/docs/usage/messages.mdx
packages/use-intl/src/core/MessageFormatCache.tsx
packages/use-intl/src/core/convertFormatsToIntlMessageFormat.tsx
packages/use-intl/src/core/createBaseTranslator.tsx
packages/use-intl/src/react/IntlContext.tsx
packages/use-intl/src/react/IntlProvider.tsx
packages/use-intl/src/react/useTranslationsImpl.tsx
packages/use-intl/test/react/useTranslations.test.tsx

Fixes #294
- Avoid creating message format instances if possible
- Introduce a cross-component message format cache

feat: Performance optimization of `useTranslations`

---

packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/server/getLocaleFromHeader.tsx
packages/next-intl/test/middleware/middleware.test.tsx

Should fix https://github.com/amannn/next-intl/discussions/446
As far as I understand the issue currently, something like this happens:
1. The middleware receives a request where the `NEXT_LOCALE` cookie is set
2. During the RSC render, the `NEXT_LOCALE` cookie is suddenly not available
If this is the case, this would fix the issue.
If however the middlware doesn't run at all for some reason, this will not make a difference. However, since this doesn't seem to have any downsides (possible since newer Next.js versions), this might simplify the code anyway and is a welcome change.

fix(RSC): Always read header in RSC render

---

docs/pages/docs/getting-started/app-router-server-components.mdx

> (...) it's important that unstable_setRequestLocale is called not only in the parent `settings/layout.tsx`, but also in the individual pages `profile/page.tsx` and `settings/page.tsx`.
```diff
- but also in the individual pages `profile/page.tsx` and `settings/page.tsx`.
+ but also in the individual pages `profile/page.tsx` and `privacy/page.tsx`.
```

fix(docs): fix small typo in the docs

---

docs/components/CodeSnippets.tsx
docs/pages/blog/3-0-release-candidate.mdx
docs/pages/blog/_meta.json
docs/pages/blog/index.mdx
docs/pages/blog/next-intl-3-0.mdx
docs/pages/blog/translations-outside-of-react-components.mdx
docs/pages/docs/getting-started/app-router-server-components.mdx
docs/theme.config.js

Accompanying PR for https://github.com/amannn/next-intl/pull/522
**TODO:**

docs: Add blog post for 3.0 RC

---

docs/pages/docs/usage/dates-times.mdx
packages/use-intl/src/core/RelativeTimeFormatOptions.tsx
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/test/core/createFormatter.test.tsx

This PR adds the `relativeTime` options to support custom units and updates the documentation accordingly.
Close: https://github.com/amannn/next-intl/issues/565

feat: Add the custom unit option of `relativeTime`

---

packages/next-intl/src/plugin.tsx

fix(RSC): Use `webpackConfig.context` instead of `process.cwd()` to detect i18n config

---

docs/pages/docs/usage/dates-times.mdx

To match the example with the above dictionary/messages json as it's currently incorrect.

docs: match example with the messages

---

examples/example-app-router/global.d.ts
packages/next-intl/src/server/getTranslations.tsx

fix: Allow usage of `getTranslations({namespace})` without TypeScript integration for messages

---

docs/pages/blog/next-intl-3-0.mdx
examples/example-app-router/src/components/NavigationLink.tsx
examples/example-app-router/src/navigation.ts
packages/next-intl/src/navigation/react-server/BaseLink.tsx
packages/next-intl/src/react-server/NextIntlClientProvider.tsx
packages/next-intl/test/react-server/NextIntlClientProvider.test.tsx

Fixes #631 
See corresponding section in the release notes: [Changes to `NextIntlClientProvider`](https://next-intl-docs.vercel.app/blog/next-intl-3-0#changes-to-nextintlclientprovider) (once this PR is merged)

fix: Don't retrieve defaults for `locale`, `now` and `timeZone` if these options have been provided to `NextIntlClientProvider`

---

docs/package.json
examples/example-app-router-migration/package.json
examples/example-app-router-next-auth/package.json
examples/example-app-router-playground/package.json
examples/example-app-router/next.config.js
examples/example-app-router/package.json
examples/example-app-router/src/app/[locale]/layout.tsx
examples/example-app-router/src/app/[locale]/page.tsx
examples/example-app-router/src/i18n.ts
examples/example-pages-router-advanced/package.json
examples/example-pages-router/package.json
packages/next-intl/package.json
packages/next-intl/src/plugin.tsx
pnpm-lock.yaml

Fixes #250 
https://github.com/amannn/next-intl/assets/4038316/94281efc-5963-46ae-a782-8d2a3f058f1f
Turbo seemingly also supports HMR for JSON files (if the path is static)—this comes in quite handy!

feat: Experimental support for `--turbo` (requires `next@^14.0.3`)

---

docs/pages/docs/routing/middleware.mdx
examples/example-app-router-next-auth/src/middleware.ts

The regex `^(/(${locales.join('|')}))?(${publicPages.join('|')})/?$` considers `/` or `/${locale}/` public.
This PR fixes that

fix(examples/with-next-auth): fix regex in middleware

---

packages/next-intl/src/plugin.tsx

fix: update example path

---

README.md
packages/next-intl/src/middleware/NextIntlMiddlewareConfig.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/middleware.test.tsx

fix: Don't set cookie on response if `localeDetection: false`

---

packages/next-intl/package.json
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/middleware.test.tsx

fix: Apply correct port and protocol during domain-based redirects when called from an internal address (e.g. from a proxy)

---

packages/next-intl/src/server/react-client/index.tsx
packages/next-intl/test/server/react-client/index.test.tsx

Fixes #685 
This is fixed for compatibility, since we've silently supported this pattern previously. However, it's still not recommended to call `getRequestConfig` in a Client Component module graph as the function can't do anything useful there. Instead, you can extract shared config like `locales` to a file like [`src/navigation.ts`](https://next-intl-docs.vercel.app/docs/routing/navigation) or any other module that is then imported into Client and Server Components.

fix: Allow to call `getRequestConfig` in outer module closure in a Client Component module graph

---

docs/pages/blog/next-intl-3-0.mdx
examples/example-app-router-migration/package.json
examples/example-app-router-next-auth/package.json
examples/example-app-router-playground/package.json
examples/example-app-router/package.json
examples/example-pages-router-advanced/package.json
examples/example-pages-router/package.json
packages/next-intl/package.json
packages/next-intl/src/react-client/useLocale.tsx
packages/next-intl/test/react-client/useLocale.test.tsx
packages/use-intl/package.json
pnpm-lock.yaml

fix: Prefer `locale` from `NextIntlClientProvider` when using `useLocale` in Client Components. `useParams().locale` is still used as a fallback.

---

packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/test/middleware/getAlternateLinksHeaderValue.test.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/next-intl/test/middleware/utils.test.tsx

When removing the default locale from a path like `/en/energy`, the middleware would erroneously remove the characters `/en` not only from the beginning, but also from the middle when redirecting to the unprefixed version (i.e. `/ergy`).
This PR is based on the fix from https://github.com/amannn/next-intl/pull/692 by @anna-colenso.

fix: Correctly normalize pathname for redirects and alternate links when `localePrefix: 'as-needed'` is used with the default locale

---

examples/example-pages-router-advanced/src/pages/404.tsx
examples/example-pages-router-advanced/src/pages/about.tsx
examples/example-pages-router-advanced/src/pages/api/hello.tsx
examples/example-pages-router-advanced/src/pages/index.tsx

Hello and thanks for a great plugin! 
This is a small PR to help save someone 20 min of debugging. It adds `.default` to awaited imports of messages in the Advanced Pages Router example. This approach is used in every other example as far as I could tell.

fix: Use .default for message imports in pages router example

---

docs/pages/docs/environments/error-files.mdx
docs/pages/docs/getting-started/app-router.mdx
docs/pages/docs/usage/configuration.mdx

this adds a missing import for `notFound` to the recently updated `i18n.ts` examples in the docs.

docs: add missing `notFound` import

---

docs/pages/docs/usage/configuration.mdx
docs/pages/docs/usage/dates-times.mdx
examples/example-app-router-playground/tests/main.spec.ts
packages/next-intl/package.json
packages/use-intl/package.json
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/test/core/createFormatter.test.tsx

Fixes #757
Previously, [`numeric: 'auto'`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat#using_the_auto_option) was used for formatting relative times. This occasionally produces incorrect output when values are rounded based on the unit, therefore it's changed to `always` now. The only exception are cases <1s which render as "now" via `numeric: 'auto'` (instead of "0 seconds ago").
**Previous behavior:**
```tsx
// Output: "Last year"
format.relativeTime(
new Date("2022-07-11T00:00:00.000Z"),
new Date("2024-01-17T00:00:00.000Z")
);
```
**New behavior:**
```tsx
// Output: "1 year ago"
format.relativeTime(
new Date("2022-07-11T00:00:00.000Z"),
new Date("2024-01-17T00:00:00.000Z")
);
```
Note that this is …

fix: Change `numeric` option from `auto` to `always` for `format.relativeTime`

---

docs/pages/docs/workflows/vscode-integration.mdx

- Changed `Inlang` to `inlang` according to brand guideline
- Added `?ref=next-intl` to the links that point to inlang.com
- Added inlang CLI as an ecosystem example

fix: update vscode-integration

---

examples/example-app-router-playground/package.json
examples/example-app-router-playground/playwright.config.ts
examples/example-app-router-playground/src/navigation.tsx
examples/example-app-router-playground/tests/locale-prefix-never.spec.ts
examples/example-app-router/messages/de.json
examples/example-app-router/messages/en.json
examples/example-app-router/tests/main.spec.ts
packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/navigation/react-client/ClientLink.tsx
packages/next-intl/src/navigation/react-client/useBaseRouter.tsx
packages/next-intl/src/navigation/shared/BaseLink.tsx
packages/next-intl/src/navigation/shared/syncLocaleCookie.tsx
packages/next-intl/src/shared/constants.tsx
packages/next-intl/test/navigation/react-client/ClientLink.test.tsx
packages/next-intl/test/navigation/react-client/useBaseRouter.test.tsx

Fixes #786
If you frequently change the locale, Next.js will at some point use the Router Cache to return a previous response immediately, not making a request to the server. This has the side effect that no `set-cookie` response header is returned that will update the locale cookie.
To address this, `next-intl` navigation APIs will now manually keep the cookie in sync.
Note that a related issue described in #786 was addressed in Next.js 14.1, so upgrading both `next` and `next-intl` is recommended.

fix: Make sure cookie value stays up to date when the Next.js Router Cache is used

---

docs/pages/docs/routing/navigation.mdx
packages/next-intl/package.json
packages/next-intl/src/navigation/react-client/createSharedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-server/createSharedPathnamesNavigation.tsx
packages/next-intl/test/navigation/createSharedPathnamesNavigation.test.tsx

Resolves https://github.com/amannn/next-intl/discussions/597

feat: Make options for `createSharedPathnamesNavigation` along with `locales` argument optional (relevant when `locales` aren't known statically)

---

docs/pages/docs/usage/lists.mdx
packages/next-intl/package.json
packages/use-intl/package.json
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/test/react/useFormatter.test.tsx

```tsx
import {useFormatter} from 'next-intl';
function Component() {
const format = useFormatter();
const users = [
{id: 1, name: 'Alice'},
{id: 2, name: 'Bob'},
{id: 3, name: 'Charlie'}
];
// Returns a `ReactNode`
return format.list(
users.map((user) => (
<a key={user.id} href={`/user/${user.id}`}>
{user.name}
</a>
))
);
}
```
As discussed in https://github.com/amannn/next-intl/discussions/840

feat: Support formatting of React elements via `format.list(…)`.

---

docs/pages/docs/routing/navigation.mdx
packages/next-intl/package.json
packages/next-intl/src/navigation/react-client/clientPermanentRedirect.tsx
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-client/createSharedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-server/createLocalizedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-server/createSharedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-server/serverPermanentRedirect.tsx
packages/next-intl/src/navigation/shared/basePermanentRedirect.tsx
packages/next-intl/test/navigation/createLocalizedPathnamesNavigation.test.tsx
packages/next-intl/test/navigation/createSharedPathnamesNavigation.test.tsx

Fixes https://github.com/amannn/next-intl/issues/715

feat: Add support for `permanentRedirect`

---

docs/pages/docs/routing/middleware.mdx

created an example for usage with the new supabase ssr package. The middleware I created is working in development as well as in production. The matcher in `middleware.ts` Was adapted based on multiple metadata files that needed to be ignored.
Suggestions on changes are welcome.
see `https://supabase.com/docs/guides/auth/auth-helpers/nextjs?language=ts` for the recommendation from supabase.

docs: Update Supabase auth example to use `@supabase/ssr`

---

examples/example-app-router-playground/tests/main.spec.ts
packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/resolveLocale.tsx
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/test/middleware/middleware.test.tsx

I noticed the same in one of my projects and thought I could look into it 🙂 . This PR should implement a case-insensitive matching mechanism for the given locales. This means that the package should treat a request with an invalid case locale, such as `de-at` or `DE`, as valid and map it correctly to `de-AT` and `de` respectively; it should also rewrite the URL to reflect the correct case, for example by rewriting `de-at` to `de-AT`.
I have done a little bit research on this topic and I think case-insensitive matching for locales makes sense to enhance the UX and avoid people mixing up uppercase and lowercase when typing in locale codes. Also, it seems to be a common practice on a lot of popular websites. Maybe it would still make sense to be able to control the behavior via a property in …

feat: Add redirects for case mismatches in locale prefixes (e.g. `/EN` → `/en`)

---

docs/pages/docs/environments/server-client-components.mdx
docs/pages/docs/routing/navigation.mdx
examples/example-app-router/src/components/LocaleSwitcherSelect.tsx

Updates LocaleSwitcherSelect.tsx in examples/example-app-router to match the doc changes in commit [de285f6](https://github.com/amannn/next-intl/commit/de285f6f78de15c51a62e2cdd29e0debcc2d415b), which fixed #581.

docs: Update `LocaleSwitcherSelect` in `example-app-router` to match docs

---

docs/pages/docs/environments/metadata-route-handlers.mdx

Just a small typo fix. Thanks for the amazing lib!

docs: Fix typo

---

packages/next-intl/src/shared/utils.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/next-intl/test/middleware/utils.test.tsx
packages/next-intl/test/shared/utils.test.tsx

Fixes #917
This works correctly now:
```
"/items/[[...slug]]": {
tr: "/ilanlar/[[...slug]]",
en: "/items/[[...slug]]",
},
```
… should match when `/tr/ilanlar` is called.

fix: Handle optional params in catch-all segments correctly when using localized pathnames

---

packages/next-intl/src/navigation/shared/BaseLink.tsx
packages/next-intl/test/navigation/react-client/ClientLink.test.tsx

fix: Handle changing href for `<Link />` correctly when using `localePrefix: 'never'`

---

packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/next-intl/test/middleware/utils.test.tsx

Fixes https://github.com/amannn/next-intl/issues/904
**Example:**
```tsx
createIntlMiddleware({
locales: ['lv', 'ru'],
defaultLocale: 'lv',
pathnames: {
'/': '/',
'/about': {
lv: '/par-mums',
ru: '/o-nas',
}
}
});
```
In this case, the only available app routes are `/lv`, `/ru`, `/lv/par-mums` and `/ru/o-nas`.
If a request for `/lv/about` or `/ru/about` is initiated, a 302 redirect to the localized alternative will now be returned.
If `en: '/about'` is added to `pathnames`, then the internal pathname becomes available—but only for this particular locale.
This PR furthermore includes a minor fix for the case where multiple localized pathnames share the same entry, but there are still variations:
```js
'/about': {
'en-UK': '/about',
'en-US': '/about',
'lv': '/par-mums'
}
```
Previously, …

feat: When using localized pathnames, allow access to internal pathnames only if they match an entry from a particular locale—otherwise redirect

---

docs/pages/docs/usage/messages.mdx
packages/use-intl/test/react/useTranslations.test.tsx

Fixes #958 
See this for reference:
```tsx
new Intl.PluralRules("en").select(0); // other
new Intl.PluralRules("lv").select(0); // zero
```

docs: Clarify usage of tags for pluralization

---

docs/pages/docs/workflows/typescript.mdx
examples/example-app-router-next-auth/global.d.ts
examples/example-app-router-playground/global.d.ts
examples/example-app-router/global.d.ts
examples/example-pages-router-advanced/global.d.ts
examples/example-pages-router/global.d.ts

docs: Update TypeScript setup to be more robust

---

docs/pages/docs/routing/middleware.mdx
examples/example-app-router-playground/messages/ja.json
examples/example-app-router-playground/src/i18n.tsx
examples/example-app-router-playground/src/navigation.tsx
examples/example-app-router-playground/tests/main.spec.ts
packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/navigation/shared/utils.tsx
packages/next-intl/test/middleware/middleware.test.tsx
packages/next-intl/test/navigation/createLocalizedPathnamesNavigation.test.tsx

Fixes #607
**Prerelease:**
```
next-intl@3.11.0-beta.2
```
**Example:**
```js
export const pathnames = {
'/': '/',
'/test': {
en: '/test',
ja: '/テスト'
}
} satisfies Pathnames<typeof locales>
```
Previously, a request to `/ja/テスト` would be a 404 since the pathname wasn't matched correctly. Now, the internal `/test` route is properly used for rendering.
If you've previously used [a workaround to encode pathnames](https://github.com/amannn/next-intl/issues/607#issuecomment-1979747515), please remove it when upgrading to the latest version of `next-intl`.

feat: Support symbols in localized pathnames that require URL encoding

---

packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/middleware.test.tsx

Fixes #658
----
@amannn to preserve your desired formatting, this project would benefit from an [EditorConfig](https://editorconfig.org/) or tool such as [Prettier](https://prettier.io/)

fix: Apply correct port when redirecting to another domain and the app doesn't run behind a proxy

---

docs/pages/docs/routing/middleware.mdx

Clerk recently release [Clerk Core 2](https://clerk.com/docs/upgrade-guides/core-2/overview) wich changes the procedure of integrating with next-intl. This PR updates the docs to reflect these changes.

docs: Update Clerk integration example to Clerk Core 2

---

docs/pages/docs/workflows/vscode-integration.mdx

Hey, we recently did a redesign/rebranding of the inlang VS Code extension.
It's now called "Sherlock" 🕵️‍♂️.
This PR reflects this change inside the `next-intl` documentation.
Happy to change anything if needed.
– Felix

docs: Rename inlang VSCode extension to Sherlock

---

docs/pages/docs/getting-started/pages-router.mdx
docs/pages/docs/usage/dates-times.mdx
packages/next-intl/package.json
packages/use-intl/package.json
packages/use-intl/src/core/createBaseTranslator.tsx
packages/use-intl/test/core/createTranslator.test.tsx
packages/use-intl/test/react/useTranslations.test.tsx
pnpm-lock.yaml

Also clarifies docs on which skeleton patterns can be used.
This increases the bundle size slightly, but being locked from upgrading the message parser isn't an option either (some dependencies like the skeleton parser were pinned by the message parser). Ultimately, we'll get rid of the ICU parser on the client side anyway: https://github.com/amannn/next-intl/pull/705.

fix: Correctly parse date skeleton `EEEE` to a long weekday like "Tuesday" (upgrades to `intl-messageformat@10` internally)

---

docs/pages/docs/usage/messages.mdx

Corrected to `en_GB`. `en_BR` would be Brazilian English :D

docs: Fix incorrect locale in example

---

packages/next-intl/package.json
packages/use-intl/package.json
packages/use-intl/src/core/RelativeTimeFormatOptions.tsx
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/test/core/createFormatter.test.tsx

feat: Support `numberingSystem` and `style` for relative time formatting

---

docs/pages/docs/environments/server-client-components.mdx
docs/pages/docs/getting-started/app-router.mdx
docs/pages/docs/usage/configuration.mdx

I know that users are frequently bitten by messages not being automatically available on the client side. We do this in the best interest of pushing performance as much as possible, but I think this has gone a bit too far. Especially when just starting out with an i18n setup, this can be frustrating.
Furthermore, I think for a number of apps this doesn't make a huge difference anyway. The number and length of messages in apps can vary significantly, so it's hard to make assumptions, but here are two examples from apps I'm maintaining:
1. An emerging one: 88 messages (1,5K gzip)
2. A more sophisticated one: 317 messages (7,6K gzip)
Apps can of course get much larger and it's important to be able to optimize, but it's questionable how early this is needed.
On top of this, app messages …

docs: Getting started with all messages on the client side

---

examples/example-app-router-next-auth/playwright.config.ts
examples/example-app-router-playground/playwright.config.ts
examples/example-app-router-playground/tests/locale-prefix-never.spec.ts
examples/example-app-router-playground/tests/main.spec.ts
examples/example-app-router/playwright.config.ts

Replace usage of `it.describe.configure({mode: 'parallel'})` with `fullyParallel: true`.
h/t https://twitter.com/sebastienlorber/status/1788165474502443345

chore: Run playwright tests in parallel

---

examples/example-app-router/src/app/[locale]/layout.tsx

Follow-up based on https://github.com/amannn/next-intl/pull/1046#pullrequestreview-2045765307

chore: Update App Router example to use `NextIntlClientProvider`

---

docs/pages/docs/getting-started/app-router.mdx

NextIntlClientProvider import statement was missing in the code snippet.
Thanks for the otherwise clear documentation!

Add missing import in code snippet

---

packages/next-intl/package.json
packages/next-intl/src/navigation/shared/basePermanentRedirect.tsx
packages/next-intl/src/navigation/shared/baseRedirect.tsx
packages/next-intl/test/navigation/shared/basePermanentRedirect.test.tsx
packages/next-intl/test/navigation/shared/baseRedirect.test.tsx

This PR addresses an issue where absolute URL's used as pathnames in the `redirect` and `permanentRedirect` functions returned from `createSharedPathnamesNavigation` are localized.
**Current behaviour:**
```ts
const { redirect, permanentRedirect } =
createSharedPathnamesNavigation({
locales: ['en-GB'],
localePrefix: 'as-needed',
})
redirect('https://example.com')
// will result in a redirect to '/en-GBhttps://example.com'
permanentRedirect('https://example.com')
// will result in a redirect to '/en-GBhttps://example.com'
```
**Expected behaviour:**
```ts
const { redirect, permanentRedirect } =
createSharedPathnamesNavigation({
locales: ['en-GB'],
localePrefix: 'as-needed',
})
redirect('https://example.com')
// will result in a redirect to 'https://example.com' …
```

fix: Handle external URLs passed to `redirect` and `permanentRedirect`

---

.prettierrc.json
docs/package.json
docs/prettier.config.js
packages/next-intl/package.json
packages/use-intl/package.json

… for docs and packages. Not for examples for the time being as this would lead to an error when a user clones an example. Publishing a prettier config and referencing it everywhere should be the final solution (see https://github.com/molindo/eslint-config-molindo/issues/99).

chore: Add prettier config

---

docs/pages/blog/next-intl-3-0.mdx
docs/pages/docs/environments/error-files.mdx
docs/pages/docs/environments/metadata-route-handlers.mdx
docs/pages/docs/routing/middleware.mdx
docs/pages/docs/usage/configuration.mdx

I encountered an incorrect anchor link for the Static Rendering Page in the documentation. The current anchor link was pointing to the wrong section, causing confusion and navigation issues.
This pull request updates the anchor link for the Static Rendering Page to point to the correct section. This ensures that users are directed to the intended part of the documentation, improving the overall user experience.

fix: Update link to Static Rendering across all the docs

---

docs/pages/docs/getting-started/app-router/without-i18n-routing.mdx

The PR removes a line of code from 'Without i18n routing documentation' which is unused in the `src/i18n.ts` file.

Removed unused code from 'Wihout i18n routing documentation'

---

packages/next-intl/package.json
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx
packages/next-intl/src/navigation/shared/utils.tsx
packages/next-intl/src/shared/utils.tsx
packages/next-intl/test/middleware/utils.test.tsx
packages/next-intl/test/navigation/react-client/createLocalizedPathnamesNavigation.test.tsx
packages/next-intl/test/shared/utils.test.tsx

Fixes #1151
Related to https://github.com/amannn/next-intl/pull/983

fix: Prefer more specific routes in `usePathname` when detecting the currently active pathname for localized pathnames

---

packages/next-intl/src/navigation/shared/redirects.tsx
packages/next-intl/src/shared/utils.tsx
packages/next-intl/test/navigation/createSharedPathnamesNavigation.test.tsx

fix: Support relative pathnames in `redirect`

---

examples/example-app-router-mixed-routing/src/middleware.ts

Passing the request headers as response headers messes with server actions. https://github.com/vercel/next.js/issues/50659 
We need to pass the updated request headers to the NextResponse's request object.

docs: Update mixed routing example with improved compatibility for Server Actions

---

docs/pages/docs/routing/middleware.mdx
examples/example-app-router-playground/next.config.mjs
examples/example-app-router-playground/package.json
examples/example-app-router-playground/playwright.config.ts
examples/example-app-router-playground/tests/getAlternateLinks.ts
examples/example-app-router-playground/tests/main.spec.ts
examples/example-app-router-playground/tests/trailing-slash.spec.ts
packages/next-intl/package.json
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.test.tsx
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/utils.tsx
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.test.tsx
packages/next-intl/src/plugin.tsx
packages/next-intl/src/shared/utils.tsx

Ref https://github.com/amannn/next-intl/issues/1184
Ref https://github.com/amannn/next-intl/issues/668

feat: Support `trailingSlash: true` in Next.js config

---

docs/pages/docs/design-principles.mdx

docs: fix typo from `specic` to `specific`

docs: fix typo in design-principles.mdx

---

packages/next-intl/package.json
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.test.tsx
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx

fix: Apply `useMemo` for `useRouter` returned from `createLocalizedPathnamesNavigation` to keep a stable reference when possible

---

packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/utils.tsx

Fixes #1207 (see issue for details)

fix: Fix open redirect vulnerability for `localePrefix: 'as-necessary'` by sanitizing pathname in the middleware

---

docs/pages/docs/routing/navigation.mdx
examples/example-app-router/src/components/LocaleSwitcherSelect.tsx
examples/example-app-router/src/types.ts

Related:
- https://github.com/amannn/next-intl/issues/1240
- https://github.com/amannn/next-intl/pull/853

docs: Adjust locale switcher example to provide more type safety

---

docs/pages/docs/environments/actions-metadata-route-handlers.mdx

Fixed case of 'host' variable in example on 'Server Actions, Metadata & Route Handlers' page.
Once the variable was written in uppercase, once in lowercase. I changed the uppercase variant to lowercase, since that is how the 'host' variable in another example is spelled.

docs: Fixed case of variable in example doc

---

docs/pages/docs/environments/actions-metadata-route-handlers.mdx
docs/pages/docs/routing/navigation.mdx
examples/example-app-router/src/app/sitemap.ts
examples/example-app-router/src/components/LocaleSwitcherSelect.tsx
examples/example-app-router/src/config.ts

docs: Clarify using params in sitemap

---

packages/next-intl/.eslintrc.js
packages/next-intl/.size-limit.ts
packages/next-intl/package.json
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.test.tsx
packages/next-intl/src/react-client/useLocale.tsx
packages/use-intl/.eslintrc.js
packages/use-intl/.size-limit.ts
packages/use-intl/package.json
packages/use-intl/src/core/formatters.tsx
packages/use-intl/src/react/IntlProvider.tsx
packages/use-intl/src/react/useTranslations.test.tsx
packages/use-intl/src/react/useTranslationsImpl.tsx
pnpm-lock.yaml

Note that not the React Compiler, but merely the ESLint plugin has been enabled.
Two very minor changes have been made that will not practically affect apps:
1. https://github.com/amannn/next-intl/pull/1281/files#diff-cc1535638f476a3c6bc0963bee2d96d868d36b3bfe54532f883bd68c8b6c7032
2. https://github.com/amannn/next-intl/pull/1281/files#diff-77b8d7665f71fbfd5b235e11a40577295255c916dc2fa688c1538d3fa7aa85ce

fix: Enable React Compiler ESLint plugin and fix relevant case

---

docs/pages/docs/usage/messages.mdx

Just copied some example code into my own code and noticed a missing curly bracket there.

docs: Add missing curly bracket

---

docs/pages/docs/routing/middleware.mdx
packages/next-intl/.size-limit.ts
packages/next-intl/src/server/react-server/getConfig.tsx

fix: Print warning for inconsistent i18n setup where no `locale` is read in `getRequestConfig` and also none is returned

---

packages/next-intl/src/server/react-server/getConfig.tsx

Fixes https://github.com/amannn/next-intl/issues/1326

fix: Add error handling in case an invalid i18n request config file has been specified

---

packages/next-intl/src/middleware/utils.test.tsx
packages/next-intl/src/middleware/utils.tsx

Consider this config:
```tsx
export const routing = defineRouting({
locales: ["en-US", "es-US"],
defaultLocale: "en-US",
localePrefix: {
mode: "always",
prefixes: {
"es-US": "/us/es",
"en-US": "/us"
},
}
});
```
… a pathname like `/us/es` would previously be incorrectly rewritten to `/en-US/es` internally. With this change, we now prioritize more specific prefixes in order to rewrite this request correctly to `/es-US`.
Fixes #1329

fix: Handle overlapping custom locale prefixes correctly

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/utils.tsx

Follow-up for https://github.com/amannn/next-intl/pull/1343, as the issue was only addressed partially before.
Closes https://github.com/amannn/next-intl/issues/1329

fix: Handle overlapping locale prefixes correctly pt. 2

---

docs/pages/docs/routing.mdx
docs/pages/docs/routing/middleware.mdx
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/resolveLocale.tsx

When a request from an unknown host like `localhost:3000` is made—as it's often the case during development—, don't try to pick a better domain when responding with redirects in the middleware. Instead, the host is now only changed for redirects if the requested host is a known one that is specified in `domains`.
Additionally, the port is now no longer removed automatically to determine a domain. This allows e.g. to pick different ports locally to test different locales.

fix: When using `domains` in routing config, handle unknown domains like `localhost:3000` more gracefully in middleware

---

docs/pages/docs/usage/configuration.mdx
packages/next-intl/.size-limit.ts
packages/use-intl/.size-limit.ts
packages/use-intl/src/react/IntlProvider.test.tsx
packages/use-intl/src/react/IntlProvider.tsx

If you have nested providers, previously only the configuration of the innermost one would be applied.
With this change, configuration is now passed from one provider to the next, while allowing to override individual props.
**BREAKING CHANGE:** There's a very rare chance that this change affects your app, but in case you've previously relied on providers not inheriting from each other, you now have to reset props manually in case you want to retain the prev. behavior.

feat!: Inherit context between providers

---

packages/next-intl/src/react-server/getTranslator.tsx
packages/next-intl/src/server/react-server/getTranslations.tsx
packages/use-intl/src/core/createBaseTranslator.tsx
packages/use-intl/src/core/createTranslator.tsx
packages/use-intl/src/react/useTranslations.tsx

Fixes https://github.com/amannn/next-intl/issues/1440

fix: Remove usage of deprecated `ReactNodeArray` which is removed in React 19

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/shared/createSharedNavigationFns.tsx

Fixes https://github.com/amannn/next-intl/issues/1438
Fixes https://github.com/amannn/next-intl/issues/1439

fix: Handle inlined search params and hashes correctly in `<Link />` from `createNavigation`

---

docs/src/pages/docs/routing/middleware.mdx
docs/src/pages/docs/workflows/typescript.mdx
packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/react-server/createNavigation.tsx
packages/next-intl/src/navigation/react-server/getServerLocale.tsx

Previously, a locale of `undefined` could have ended up in your navigation APIs in case the middleware didn't run as part of the request and `setRequestLocale` wasn't used. Now, we resolve from `i18n/request.ts` for this case too, potentially taking a fallback locale into account.
Note however that this is more often than not the result of an invalid middleware config (see [middleware troubleshooting](https://next-intl-docs.vercel.app/docs/routing/middleware#troubleshooting)).

fix: Resolve locale for navigation APIs consistently from `i18n/request.ts` in `react-server` like all other APIs do (#1459)

---

package.json
packages/next-intl/.size-limit.ts
packages/next-intl/package.json
pnpm-lock.yaml

Doesn't contain any relevant changes, but good that it's past the 0.x range now.
https://github.com/jshttp/negotiator/releases/tag/v1.0.0
https://npmdiff.dev/negotiator/0.6.4/1.0.0/

fix: Upgrade to `negotiator@^1.0`

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/shared/BaseLink.tsx

fix: Don't warn when setting `prefetch={true}` on `<Link />`

---

docs/src/pages/docs/workflows/typescript.mdx
packages/next-intl/package.json
packages/next-intl/src/middleware/middleware.tsx

If you don't use TypeScript, this change doesn't affect you.

feat!: Bump minimum required `typescript` version to 5 for projects using TypeScript

---

packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/server/react-client/index.test.tsx
packages/next-intl/src/server/react-client/index.tsx
packages/next-intl/src/server/react-server/getConfig.tsx
packages/next-intl/src/server/react-server/getRequestConfig.tsx
packages/next-intl/src/server/react-server/index.tsx

**Changes**
- Removed deprecated second argument of `createMiddleware` (use first argument instead, ideally via `defineRouting`)
- Remove deprecated `({locale})` argument in `getRequestConfig` (use `({requestLocale})` instead)
- Remove deprecated `unstable_setRequestLocale` (use `setRequestLocale` instead)

feat!: Remove deprecated APIs pt. 2

---

docs/src/pages/docs/routing.mdx
docs/src/pages/docs/routing/middleware.mdx
examples/example-app-router-playground/tests/base-path.spec.ts
examples/example-app-router-playground/tests/domains.spec.ts
examples/example-app-router-playground/tests/locale-cookie-false.spec.ts
examples/example-app-router-playground/tests/locale-prefix-never.spec.ts
examples/example-app-router-playground/tests/main.spec.ts
examples/example-app-router-playground/tests/trailing-slash.spec.ts
examples/example-app-router-playground/tests/utils.ts
examples/example-app-router/tests/main.spec.ts
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/src/middleware/syncCookie.tsx
packages/next-intl/src/navigation/react-client/createNavigation.test.tsx
packages/next-intl/src/routing/config.tsx

**Changes**
1. The `maxAge` attribute of the locale cookie is decreased from 1 year to 5 hours in order to be GDPR-compliant.
2. The locale cookie is now only set when the user's language doesn't match a requested locale. E.g. a user with `accept-language: 'en'` will cause a cookie to be set when `/de` is requested to remember the preference for `de`.
3. `localeDetection: false` previously ambiguously also disabled the cookie from being set. This is no longer the case. For consistency, you can now use the explicit [`localeCookie: false`](https://next-intl-docs.vercel.app/docs/routing#locale-cookie) option instead.
If you want to increase the cookie expiration, you can use the [`maxAge`](https://next-intl-docs.vercel.app/docs/routing#locale-cookie) attribute to do so:
```tsx
import …
```

feat!: Decrease cookie expiration to 5 hours, only set cookie when necessary and only disable cookie if `localeCookie: false` is set

---

packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx

`normalizeTrailingSlash` expects a `pathname` but it's getting pathname + search. 
This causes redirects to urls like `/users/?sort=asc/`

fix: Correctly handle search params in redirects when using `trailingSlash: true`

---

docs/src/pages/docs/routing.mdx
docs/src/pages/docs/workflows/typescript.mdx

This PR enhances the **TypeScript Integration** and **Routing** sections of the `next-intl` documentation by:
- Specifying **TypeScript version 5** or later as a requirement for compatibility with `next-intl`.
- Adding a troubleshooting tip under the **Define routing** section to help developers resolve a common TypeScript error.
---
1. **TypeScript Version Requirement**: 
- Updated the TypeScript Integration section to recommend **TypeScript version 5 or later** to prevent issues such as `TS2554: Expected 0 arguments, but got 1`.
- This provides users with upfront guidance to avoid compatibility issues.
2. **New Troubleshooting Detail**:
- Added a `Details` section in **Define routing** explaining how to resolve the `TS2554` TypeScript error by upgrading to TypeScript 5 or later.
- This …

docs: clarify TypeScript version requirement and add troubleshooting for TypeScript error

---

docs/src/pages/docs/usage/configuration.mdx
docs/src/pages/docs/usage/dates-times.mdx
examples/example-app-router-playground/next.config.mjs
examples/example-app-router-playground/src/i18n/request.tsx
packages/next-intl/src/react-server/NextIntlClientProviderServer.test.tsx
packages/next-intl/src/react-server/NextIntlClientProviderServer.tsx
packages/next-intl/src/react-server/useFormatter.test.tsx
packages/next-intl/src/react-server/useFormatter.tsx
packages/next-intl/src/react-server/useNow.tsx
packages/next-intl/src/react-server/useTranslations.test.tsx
packages/next-intl/src/react-server/useTranslations.tsx
packages/next-intl/src/server/react-server/getConfig.tsx
packages/next-intl/src/server/react-server/getConfigNow.tsx
packages/next-intl/src/server/react-server/getDefaultNow.tsx
packages/next-intl/src/server/react-server/getFormats.tsx
packages/next-intl/src/server/react-server/getFormatter.test.tsx
packages/next-intl/src/server/react-server/getFormatter.tsx
packages/next-intl/src/server/react-server/getNow.tsx
packages/next-intl/src/server/react-server/getServerFormatter.tsx
packages/next-intl/src/server/react-server/getServerTranslator.tsx
packages/next-intl/src/server/react-server/getTranslations.test.tsx
packages/next-intl/src/server/react-server/getTranslations.tsx
packages/next-intl/src/server/react-server/getTranslator.tsx
packages/use-intl/.size-limit.ts
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/src/react/useFormatter.test.tsx
packages/use-intl/src/react/useNow.tsx
turbo.json

In preparation for [`dynamicIO`](https://nextjs.org/docs/canary/app/api-reference/config/next-config-js/dynamicIO) and [`ppr`](https://nextjs.org/docs/app/api-reference/next-config-js/ppr), the default of `now={new Date()}` on `NextIntlClientProvider` has been removed for usage in Client Components.
While you can restore this behavior by adding [`now: new Date()`](https://next-intl-docs.vercel.app/docs/usage/configuration#now) in your `i18n/request.ts` config, the [relative time formatting docs](https://next-intl-docs-git-feat-dio-now-next-intl.vercel.app/docs/usage/dates-times#relative-times) now suggest a slightly adapted pattern with some benefits:
1. Always pass an explicit `now` argument to `format.relativeTime(date, now)` instead of relying on a global default
2. `now` can …

feat!: Remove default of `now={new Date()}` from `NextIntlClientProvider` for usage with `format.relativeTime`  (preparation for `dynamicIO`)

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/react-client/createLocalizedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-client/createNavigation.test.tsx
packages/next-intl/src/navigation/react-client/createNavigation.tsx
packages/next-intl/src/navigation/react-client/createSharedPathnamesNavigation.tsx
packages/next-intl/src/navigation/react-client/useBasePathname.test.tsx
packages/next-intl/src/navigation/react-client/useBasePathname.tsx
packages/next-intl/src/shared/utils.tsx

Fixes https://github.com/amannn/next-intl/issues/1568

fix: Handle inconsistency in Next.js when using `usePathname` with custom prefixes, `localePrefix: 'as-needed'` and static rendering

---

packages/next-intl/src/navigation/react-client/createNavigation.test.tsx
packages/next-intl/src/navigation/react-client/useBasePathname.tsx

fix: Follow-up for #1573 to also handle the case when a non-default locale is in use

---

packages/next-intl/src/server/react-server/getTranslations.tsx

See https://github.com/amannn/next-intl/discussions/437#discussioncomment-11593318

fix: Support `t.has` when `getTranslations` is called with an object argument

---

docs/src/pages/docs/routing.mdx
examples/example-app-router/tests/main.spec.ts
packages/next-intl/src/navigation/react-client/createNavigation.test.tsx
packages/next-intl/src/routing/config.tsx

Initially, I planned to add an expiration of 5 hours to the locale cookie for `next-intl@4` to comply with GDPR regulations. However, this has the implication that if the browser remains open for longer than 5 hours, the cookie can be reset in the middle of a session.
Due to this, it seems more reasonable to not set an expiration at all, turning the cookie into a session cookie. Session cookies expiry only when a browser is closed. On mobile, this can be even more beneficial, as browsers are rarely closed (the browser can clear cookies though if memory is constrained).

fix: Make locale cookie a session cookie

---

packages/use-intl/src/core/IntlConfig.tsx
packages/use-intl/src/core/createTranslator.tsx

Ref: https://x.com/ddunderfelt/status/1874403640515121642

feat: Allow overriding typed `Messages` when using `createTranslator`

---

docs/src/pages/docs/environments/actions-metadata-route-handlers.mdx
examples/example-app-router-playground/src/middleware.ts
examples/example-app-router-playground/tests/main.spec.ts

docs: Consider custom prefixes for open graph images

---

docs/src/components/GetStartedBackground.tsx

Hi! I'd just like to make a small fix to the site's landing page.
`width: 100vw` causes appearing of a horizontal scrollbar:
You can read more about the reasons for this behavior, for example, [here](https://dev.to/tepythai/why-100vw-causes-horizontal-scrollbar-4nlm), but in brief, on Windows, the vertical scrollbar occupies part of the viewport but `100vw` doesn't include the vertical scrollbar's width into its calculation, so there is not enough space for a block with `width: 100vw`. The fix is very simple: use `100%` instead of `100vw`.
In the next-intl case, `width: 100vw` is set on the `<svg>` element at the bottom of the page:
I tested the fix, and it doesn't break the layout at any screen breakpoints:

docs: Fix horizontal scroll on the landing page

---

docs/src/pages/docs/environments/server-client-components.mdx
docs/src/pages/docs/getting-started/app-router/with-i18n-routing.mdx
docs/src/pages/docs/getting-started/app-router/without-i18n-routing.mdx
docs/src/pages/docs/usage/configuration.mdx
examples/example-app-router-migration/src/app/[locale]/layout.tsx
examples/example-app-router-mixed-routing/src/app/(public)/[locale]/layout.tsx
examples/example-app-router-mixed-routing/src/app/app/layout.tsx
examples/example-app-router-single-locale/src/app/layout.tsx
examples/example-app-router-without-i18n-routing/src/app/layout.tsx
examples/example-app-router/src/components/BaseLayout.tsx
packages/next-intl/.size-limit.ts
packages/next-intl/src/react-server/NextIntlClientProviderServer.test.tsx
packages/next-intl/src/react-server/NextIntlClientProviderServer.tsx
packages/next-intl/src/server/react-server/getConfig.tsx
packages/next-intl/src/server/react-server/getServerFormatter.tsx
packages/use-intl/.size-limit.ts
packages/use-intl/src/core/IntlConfig.tsx
packages/use-intl/src/core/initializeConfig.tsx
packages/use-intl/src/react/IntlProvider.test.tsx
packages/use-intl/src/react/IntlProvider.tsx

This makes it easier to get started. If you don't want this behavior, you can still opt-out via `messages={null}`.
**TODO**

feat: Inherit messages by default in `NextIntlClientProvider`

---

docs/src/pages/docs/usage/dates-times.mdx
docs/src/pages/docs/usage/numbers.mdx
packages/next-intl/.size-limit.ts
packages/use-intl/.size-limit.ts
packages/use-intl/src/core/createFormatter.test.tsx
packages/use-intl/src/core/createFormatter.tsx
packages/use-intl/src/react/useFormatter.test.tsx

**Example:**
```tsx
formatter.dateTime(date, 'short', {
timeZone: 'America/New_York'
})
```

feat: Allow to override options of global formats

---

docs/src/pages/docs/usage/configuration.mdx

Update doc to fix the closing tag.

docs: Fix typo with closing tag

---

packages/next-intl/.size-limit.ts
packages/next-intl/__mocks__/react.tsx
packages/next-intl/src/navigation/shared/createSharedNavigationFns.tsx
packages/next-intl/src/react-server/index.test.tsx
packages/next-intl/src/server/react-server/RequestLocale.tsx
packages/next-intl/src/server/react-server/getConfig.tsx
packages/next-intl/src/shared/utils.tsx

fix: Add workaround for OpenTelemetry/Zone.js

---

docs/src/pages/docs/getting-started/app-router/with-i18n-routing.mdx
docs/src/pages/docs/routing.mdx
docs/src/pages/docs/routing/middleware.mdx
examples/example-app-router-migration/src/middleware.ts
examples/example-app-router-mixed-routing/src/middleware.ts
examples/example-app-router-mixed-routing/tests/main.spec.ts
examples/example-app-router-next-auth/src/middleware.ts
examples/example-app-router/src/middleware.ts
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.test.tsx
packages/next-intl/src/middleware/getAlternateLinksHeaderValue.tsx
packages/next-intl/src/middleware/middleware.test.tsx

Previously, we suggested a middleware matcher that looked like this:
```tsx
// middleware.ts
export const config = {
// Match only internationalized pathnames
matcher: ['/', '/(de|en)/:path*']
};
```
Even though the hardcoded locales need to be updated when new locales are added, this was suggested in light of providing an error-free getting started experience.
However, based on the apps I've seen over time, it seems like this choice was unpopular and users typically go for a matcher that looks like this:
```tsx
export const config = {
// Match all pathnames except for
// - … if they start with `/api`, `/_next` or `/_vercel`
// - … the ones containing a dot (e.g. `favicon.ico`)
matcher: '/((?!api|_next|_vercel|.*\\..*).*)'
};
```
While this avoids hardcoding locales, it requires extra …

fix!: Return `x-default` alternate link also for sub pages when using `localePrefix: 'always'` and update middleware matcher suggestion in docs

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/shared/createSharedNavigationFns.tsx

Fixes #1731 
Many thanks to @seanpavlov for analyzing the issue and suggesting the fix!

fix: Handle `query` in `<Link />` correctly when using `localePrefix: 'as-needed'` with `domains`

---

docs/src/components/HeroCode.tsx

Fixed the capitalization in `firstName` variable

docs: fix variable name on landing page example

---

docs/src/pages/docs/routing/middleware.mdx

1. change `protect` usage to latest version
2. add locale prefix matcher and non locale prefix matcher at the same time to avoid infinite redirect
Fixes https://github.com/amannn/next-intl/issues/1458

docs: Update Clerk example in middleware docs

---

docs/src/pages/blog/next-intl-4-0.mdx
docs/src/pages/docs/environments/_meta.tsx
docs/src/pages/docs/environments/testing.mdx
examples/example-app-router-playground/jest.config.js
examples/example-app-router/jest.config.js
examples/example-pages-router-advanced/jest.config.js

Somehow the Jest examples in this repo still worked, but if you try to use `next-intl` outside of this monorepo there was an issue with Jest. The problem is that Jest doesn't support ESM (see e.g. https://github.com/vercel/next.js/issues/40183).
Ref https://github.com/amannn/next-intl/issues/1796

docs: Update Jest examples

---

docs/src/pages/docs/getting-started/app-router/with-i18n-routing.mdx

Remove unused...
```ts
import {createNavigation} from 'next-intl/navigation';
```
...import in `routing.ts` setup example on _app-router -> with-18n-routing_ page.

docs: Remove unused createNavigation import in routing.ts setup example

---

docs/src/pages/docs/routing.mdx
docs/src/pages/docs/routing/navigation.mdx

[Ref](https://github.com/amannn/next-intl/discussions/1807)

docs: Clarify prefixed link `href` with `localePrefix: 'as-needed'`

---

docs/tsconfig.json

This makes MDX files part of the TypeScript program in the editor. As a result, MDX IntelliSense uses the same configuration as the rest of the program. This also means TypeScript only needs to provide IntelliSense for one program instead of using a default fallback for MDX. This improves performance.
Before:
After:

chore: add MDX files to tsconfig include pattern

---

docs/src/styles.css

I noticed that the logotype was not visible so I investigated.
It looks like the CSS variables were specified incorrectly.
**Target page:** [Examples – Internationalization (i18n) for Next.js](https://next-intl.dev/examples)
**Screenshots:**
<kbd> ![image](https://github.com/user-attachments/assets/1aac7c8f-e613-42dc-8f92-af49a15c8212)
Before | After
-|-

docs: Fix navbar background

---

packages/use-intl/src/core/createTranslator.test.tsx
packages/use-intl/src/core/createTranslator.tsx

**Example**:
```tsx
const t = useTranslations();
t('label', {count: 123456789123456789123456n});
```
Fixes #1928

feat: Support BigInt for `number` interpolation with `useTranslations`

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/shared/utils.tsx
packages/next-intl/src/shared/utils.test.tsx
packages/next-intl/src/shared/utils.tsx

Addresses https://github.com/amannn/next-intl/discussions/1932
**Prerelease:**
```
npm install next-intl@0.0.0-canary-4ada87c
```

fix: Don't encode hashes in unknown pathnames

---

packages/next-intl/src/plugin/hasStableTurboConfig.tsx

As discussed in https://github.com/amannn/next-intl/discussions/1943, this adds a flightly friendlier error message for when `createRequire` is accidentally ran in an unexpected environment.

fix: Add friendly error message when failing to load current Next.js version

---

packages/use-intl/src/core/createBaseTranslator.tsx
packages/use-intl/src/react/useTranslations.test.tsx

fix: Correctly compile messages containing escaped curly braces (e.g. `'{name'}`)

---

examples/example-app-router-playground/src/app/[locale]/page.tsx
examples/example-app-router-playground/src/components/ClientRouter.tsx
examples/example-app-router-playground/tests/main.spec.ts
packages/next-intl/src/navigation/react-client/createNavigation.test.tsx
packages/next-intl/src/navigation/react-client/createNavigation.tsx
packages/next-intl/src/navigation/shared/BaseLink.tsx

fix: Prefix pathnames when switching with `useRouter` to another locale

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx

Previously, we always called `.rewrite` just in case since it did no harm, but it seems like this messes with Vercel observability tools. This cleans it up to only call this function when really necessary.

fix: Only call `NextResponse.rewrite` if really necessary
