CHANGELOG.md
packages/next-intl/package.json
packages/next-intl/src/useTranslations.tsx
packages/next-intl/test/useTranslations.test.tsx

fix: Accept empty messages

---

packages/use-intl/CHANGELOG.md
packages/use-intl/package.json
packages/use-intl/src/IntlError.tsx

Export IntlErrorCode for JavaScript users

---

README.md
packages/use-intl/CHANGELOG.md
packages/use-intl/package.json
packages/use-intl/src/IntlContext.tsx
packages/use-intl/src/IntlProvider.tsx
packages/use-intl/src/useIntl.tsx
packages/use-intl/test/useIntl.test.tsx

feat: Add support for customising time zones

---

packages/example/.eslintrc.js
packages/example/next.config.js
packages/example/package.json
packages/next-intl/package.json
yarn.lock

feat: Support latest Next.js version

---

packages/use-intl/src/useTranslations.tsx
packages/use-intl/test/useTranslations.test.tsx

fix(cacheing): Include namespace in formatting cache key

---

packages/example-advanced/.eslintrc.js
packages/example-advanced/package.json
packages/example-advanced/src/pages/index.tsx
packages/example/package.json
packages/website/components/CodeSandbox.tsx
packages/website/next.config.js
packages/website/pages/docs/installation.mdx
packages/website/pages/docs/usage/index.mdx
packages/website/pages/examples/advanced.mdx
packages/website/pages/examples/meta.json
packages/website/pages/examples/minimal.mdx
packages/website/pages/index.mdx
packages/website/pages/meta.json
yarn.lock

Relates to https://github.com/amannn/next-intl/issues/72

docs: Interactive examples

---

packages/use-intl/src/validateMessages.tsx
packages/use-intl/test/useTranslations.test.tsx

fix: Allow null message values

---

packages/website/pages/docs/usage/error-handling.mdx

See https://github.com/amannn/next-intl/discussions/123

docs: Fallbacks from other locales

---

packages/use-intl/test/useTranslations.test.tsx
packages/website/pages/docs/usage/dates-times.mdx
packages/website/pages/docs/usage/numbers.mdx
packages/website/pages/docs/usage/typescript.mdx

docs: Fix docs for number skeletons

---

packages/use-intl/src/core/createBaseTranslator.tsx
packages/use-intl/test/react/useTranslations.test.tsx

fix: Return up-to-date translations when messages change

---

packages/website/pages/docs/next-13/client-components.mdx

fix: deprecated import

---

.github/workflows/main.yml
.github/workflows/publish.yml
package.json
packages/example-advanced/package.json
packages/example-next-13-next-auth/package.json
packages/example-next-13/package.json
packages/example/package.json
packages/next-intl/package.json
packages/next-intl/src/react-server/index.tsx
packages/website/package.json
scripts/publish.js
yarn.lock

Also update Next.js and add provenance.

fix: Improve error message when trying to use `next-intl` APIs in RSC

---

docs/package.json
docs/pages/docs/next-13/middleware.mdx
docs/theme.config.js
examples/example-advanced/package.json
examples/example-next-13-next-auth/package.json
examples/example-next-13/.gitignore
examples/example-next-13/next.config.js
examples/example-next-13/package.json
examples/example-next-13/src/app/[locale]/layout.tsx
examples/example-next-13/src/app/page.tsx
examples/example/package.json
packages/next-intl/package.json
pnpm-lock.yaml

Closes #334
Closes #313
Closes #330

docs: Static export and update Next.js in examples

---

docs/pages/docs/usage/messages.mdx

Based on https://github.com/amannn/next-intl/pull/365/

docs: Add docs for RTL languages

---

docs/pages/docs/usage/numbers.mdx
packages/use-intl/src/core/convertFormatsToIntlMessageFormat.tsx
packages/use-intl/test/react/useFormatter.test.tsx
packages/use-intl/test/react/useTranslations.test.tsx

fix: Apply time zone for default formats

---

docs/pages/docs/getting-started/app-router-server-components.mdx
docs/pages/docs/routing/index.mdx
docs/pages/docs/routing/middleware.mdx
docs/pages/docs/routing/navigation.mdx
docs/pages/index.mdx

See https://github.com/amannn/next-intl/pull/426
**TODO**:

docs: Provide docs for pathname localization

---

packages/next-intl/src/middleware/middleware.tsx
packages/next-intl/test/middleware/middleware.test.tsx

Fixes https://github.com/amannn/next-intl/issues/568

fix(RSC): Fixed the search not being added on localized pathname redirects

---

docs/package.json
docs/pages/docs/environments/metadata-route-handlers.mdx
examples/example-advanced/package.json
examples/example-next-13-next-auth/package.json
examples/example-next-13/package.json
examples/example/package.json
packages/next-intl/package.json
pnpm-lock.yaml

feat: Support Next.js 14

---

.github/ISSUE_TEMPLATE/update_docs.yml
docs/components/Footer.tsx
docs/config.js
docs/next-sitemap.config.js
docs/next.config.js
docs/theme.config.tsx

Fixes https://github.com/amannn/next-intl/discussions/652#discussioncomment-7644001

docs: Fix feedback link

---

docs/pages/docs/routing/middleware.mdx

Based on [this answer](https://github.com/amannn/next-intl/discussions/422#discussioncomment-6529565) with a little improvements.

docs: Add Supabase Authentication example

---

examples/example-app-router/tsconfig.json
packages/next-intl/src/server/react-client/index.tsx
packages/next-intl/src/server/react-server/createRequestConfig.tsx
packages/next-intl/src/server/react-server/getConfig.tsx
packages/next-intl/src/server/react-server/getFormatter.tsx
packages/next-intl/src/server/react-server/getMessages.tsx
packages/next-intl/src/server/react-server/getNow.tsx
packages/next-intl/src/server/react-server/getTimeZone.tsx
packages/next-intl/src/server/react-server/getTranslations.tsx
packages/next-intl/test/server/react-server/index.test.tsx
packages/next-intl/tsconfig.json
packages/use-intl/src/core/initializeConfig.tsx

fix: Fix compatibility with `moduleResolution: 'Bundler'`

---

docs/pages/docs/usage/configuration.mdx

You can't use HTML tags in TS code like that, you will always get an error, please accept this changes so the documentation is correct. Thank you!

fix: Can't use HTML code on TS files like that

---

packages/next-intl/package.json
packages/next-intl/src/navigation/shared/syncLocaleCookie.tsx
packages/next-intl/test/navigation/react-client/useBaseRouter.test.tsx

fix: Keep cookie value in sync when navigating within a locale

---

docs/pages/docs/getting-started/app-router.mdx

docs: Fix export statement in `next.config.js`

---

docs/pages/docs/routing/middleware.mdx

Hey,
As requested [here](https://github.com/amannn/next-intl/issues/846), I've update the doc about the ongoing revalidation issue
Fixes #846

docs: update `middleware.mdx` doc about revalidation issue

---

docs/pages/docs/usage/configuration.mdx
docs/theme.config.tsx
packages/next-intl/src/react-server/NextIntlClientProviderServer.tsx
packages/next-intl/src/react-server/index.tsx
packages/next-intl/test/react-server/NextIntlClientProviderServer.test.tsx

docs: defaultTranslationMessages with NextIntlClientProvider

---

docs/pages/index.mdx
packages/next-intl/package.json
packages/next-intl/src/navigation/react-client/useBaseRouter.tsx
packages/next-intl/src/navigation/shared/syncLocaleCookie.tsx
packages/next-intl/src/navigation/shared/utils.tsx
packages/next-intl/src/shared/utils.tsx
packages/next-intl/test/navigation/react-client/useBaseRouter.test.tsx

fix: Incorporate `basePath` correctly in `useRouter` functions

---

docs/pages/docs/usage/messages.mdx

I think this is a typo in the docs?

docs: Fix typo

---

docs/components/AlgoliaSearch.css
docs/components/AlgoliaSearch.tsx
docs/components/Hero.tsx
docs/package.json
docs/pages/blog/next-intl-3-0.mdx
docs/pages/docs/usage/messages.mdx
docs/styles.css
docs/theme.config.tsx
pnpm-lock.yaml

Tested styling variations:
```
states
dark mode
home
mobile
desktop
other
mobile
desktop
light mode
home
mobile
desktop
other
mobile
desktop
```

docs: Add Algolia search

---

docs/pages/docs/routing/navigation.mdx
docs/pages/docs/workflows.mdx
docs/pages/docs/workflows/_meta.json
docs/pages/docs/workflows/linting.mdx

This PR adds basic docs for linting, based on discussions in #1036.
We could maybe add biomejs examples as well seeing as it is rising in popularity?
Let me know if we want any more changes

docs: add documentation for linting with basic examples

---

docs/pages/docs/environments/server-client-components.mdx

found a reference to useFormState which was renamed in react-19-rc to useActionState
see: https://react.dev/reference/react/useActionState

fix: update react19 api

---

docs/pages/docs/routing/middleware.mdx

Update docs regarding routing middleware when integrating Supabase Auth.
Resolves https://github.com/amannn/next-intl/issues/1228
Resolves https://github.com/amannn/next-intl/issues/719

docs: Update regarding routing middleware when integrating Supabase Auth

---

docs/pages/docs/design-principles.mdx
docs/pages/docs/environments/error-files.mdx
docs/pages/docs/usage/configuration.mdx
docs/pages/docs/usage/lists.mdx
docs/pages/docs/usage/messages.mdx

Fixed some typos I found while reading the docs.

docs: Fix typos

---

docs/app/robots.tsx

docs: Add robots.txt

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/middleware/middleware.test.tsx
packages/next-intl/src/middleware/middleware.tsx

fix: Handle malformed pathnames in middleware

---

.npmrc
examples/example-app-router-migration/package.json
examples/example-app-router-mixed-routing/package.json
examples/example-app-router-next-auth/package.json
examples/example-app-router-playground/package.json
examples/example-app-router-single-locale/package.json
examples/example-app-router-without-i18n-routing/package.json
examples/example-app-router/package.json
examples/example-pages-router-advanced/package.json
examples/example-pages-router-legacy/package.json
examples/example-pages-router/package.json
examples/example-remix/package.json
examples/example-use-intl/package.json
pnpm-lock.yaml

See https://github.com/pnpm/pnpm/issues/5907

chore: Use local versions correctly

---

packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/react-server/getServerLocale.tsx

fix: Lazy import config into `next-intl/navigation` (`react-server`)

---

examples/example-app-router-playground/src/components/TypePortabilityTest.ts
packages/use-intl/src/core/IntlConfig.tsx
packages/use-intl/src/core/createTranslator.tsx
packages/use-intl/src/core/types.tsx
packages/use-intl/src/react/useTranslations.test.tsx

([ref](https://github.com/amannn/next-intl/discussions/1631#discussioncomment-11751429))

fix: Accept a deep partial of `Messages` for `messages` prop of provider

---

docs/src/pages/blog/next-intl-4-0.mdx

Related to https://github.com/amannn/next-intl/pull/1682

docs: V4 beta provider inheritance

---

docs/src/pages/docs/workflows/_meta.tsx
docs/src/pages/docs/workflows/messages.mdx
examples/example-app-router-playground/messages/ja.json

Ref: https://github.com/lingualdev/i18n-check/issues/37

docs: Add `i18n-check` to workflows & integrations

---

docs/src/pages/docs/routing/navigation.mdx
packages/next-intl/.size-limit.ts
packages/next-intl/src/navigation/createNavigation.test.tsx
packages/next-intl/src/navigation/shared/createSharedNavigationFns.tsx

Resolves https://github.com/amannn/next-intl/issues/1845

feat: Add `forcePrefix` option for `redirect` and `getPathname`

---

examples/example-app-router-playground/src/app/[locale]/client/ClientContent.tsx
examples/example-app-router-playground/tests/main.spec.ts
packages/next-intl/src/navigation/react-client/createNavigation.tsx

fix: Ensure cookie is synced before navigation with `useRouter`
